# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_iOsCalculator(object):
    def setupUi(self, iOsCalculator):
        iOsCalculator.setObjectName("iOsCalculator")
        iOsCalculator.resize(400, 600)
        iOsCalculator.setMinimumSize(QtCore.QSize(400, 600))
        iOsCalculator.setMaximumSize(QtCore.QSize(400, 600))
        iOsCalculator.setStyleSheet("background-color: rgb(6, 6, 6);")
        self.centralwidget = QtWidgets.QWidget(iOsCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.natija_label = QtWidgets.QLabel(self.centralwidget)
        self.natija_label.setGeometry(QtCore.QRect(0, 0, 400, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.natija_label.setFont(font)
        self.natija_label.setStyleSheet("background-color: rgb(9, 9, 9);\n"
"color: rgb(254, 254, 254);\n"
"font: 40px;")
        self.natija_label.setObjectName("natija_label")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(0, 100, 100, 100))
        self.clear_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(150, 150, 150);\n"
"border-radius:50px;\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:  rgb(255, 255, 255);\n"
"color: rgb(7, 7, 7);\n"
"}")
        self.clear_button.setObjectName("clear_button")
        self.changeDirection_button = QtWidgets.QPushButton(self.centralwidget)
        self.changeDirection_button.setGeometry(QtCore.QRect(100, 100, 100, 100))
        self.changeDirection_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.changeDirection_button.setFont(font)
        self.changeDirection_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(150, 150, 150);\n"
"border-radius:50px;\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:  rgb(255, 255, 255);\n"
"color: rgb(7, 7, 7);\n"
"}")
        self.changeDirection_button.setObjectName("changeDirection_button")
        self.percent_button = QtWidgets.QPushButton(self.centralwidget)
        self.percent_button.setGeometry(QtCore.QRect(200, 100, 100, 100))
        self.percent_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.percent_button.setFont(font)
        self.percent_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(150, 150, 150);\n"
"border-radius:50px;\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:  rgb(255, 255, 255);\n"
"color: rgb(7, 7, 7);\n"
"}")
        self.percent_button.setObjectName("percent_button")
        self.divide_button = QtWidgets.QPushButton(self.centralwidget)
        self.divide_button.setGeometry(QtCore.QRect(300, 100, 100, 100))
        self.divide_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.divide_button.setFont(font)
        self.divide_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 136, 0);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 136, 0);\n"
"}")
        self.divide_button.setObjectName("divide_button")
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setGeometry(QtCore.QRect(100, 200, 100, 100))
        self.button_8.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_8.setFont(font)
        self.button_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_8.setObjectName("button_8")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setGeometry(QtCore.QRect(0, 200, 100, 100))
        self.button_7.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_7.setFont(font)
        self.button_7.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_7.setObjectName("button_7")
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setGeometry(QtCore.QRect(200, 200, 100, 100))
        self.button_9.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_9.setFont(font)
        self.button_9.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_9.setObjectName("button_9")
        self.multiply_button = QtWidgets.QPushButton(self.centralwidget)
        self.multiply_button.setGeometry(QtCore.QRect(300, 200, 100, 100))
        self.multiply_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.multiply_button.setFont(font)
        self.multiply_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 136, 0);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 136, 0);\n"
"}")
        self.multiply_button.setObjectName("multiply_button")
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setGeometry(QtCore.QRect(100, 300, 100, 100))
        self.button_5.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_5.setFont(font)
        self.button_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_5.setObjectName("button_5")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setGeometry(QtCore.QRect(0, 300, 100, 100))
        self.button_4.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_4.setFont(font)
        self.button_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_4.setObjectName("button_4")
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setGeometry(QtCore.QRect(200, 300, 100, 100))
        self.button_6.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_6.setFont(font)
        self.button_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_6.setObjectName("button_6")
        self.minus_button = QtWidgets.QPushButton(self.centralwidget)
        self.minus_button.setGeometry(QtCore.QRect(300, 300, 100, 100))
        self.minus_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.minus_button.setFont(font)
        self.minus_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 136, 0);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 136, 0);\n"
"}")
        self.minus_button.setObjectName("minus_button")
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setGeometry(QtCore.QRect(100, 400, 100, 100))
        self.button_2.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_2.setFont(font)
        self.button_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_2.setObjectName("button_2")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setGeometry(QtCore.QRect(0, 400, 100, 100))
        self.button_1.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_1.setFont(font)
        self.button_1.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_1.setObjectName("button_1")
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setGeometry(QtCore.QRect(200, 400, 100, 100))
        self.button_3.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_3.setFont(font)
        self.button_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_3.setObjectName("button_3")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(300, 400, 100, 100))
        self.add_button.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_button.setFont(font)
        self.add_button.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 136, 0);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 136, 0);\n"
"}")
        self.add_button.setObjectName("add_button")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setGeometry(QtCore.QRect(0, 500, 200, 100))
        self.button_0.setMinimumSize(QtCore.QSize(200, 100))
        self.button_0.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_0.setFont(font)
        self.button_0.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_0.setObjectName("button_0")
        self.button_comma = QtWidgets.QPushButton(self.centralwidget)
        self.button_comma.setGeometry(QtCore.QRect(200, 500, 100, 100))
        self.button_comma.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_comma.setFont(font)
        self.button_comma.setStyleSheet("QPushButton{\n"
"background-color: rgb(58, 58, 58);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(112, 112, 112);\n"
"}")
        self.button_comma.setObjectName("button_comma")
        self.button_equal = QtWidgets.QPushButton(self.centralwidget)
        self.button_equal.setGeometry(QtCore.QRect(300, 500, 100, 100))
        self.button_equal.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_equal.setFont(font)
        self.button_equal.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 136, 0);\n"
"border-radius:50px;\n"
"color: rgb(255, 255, 255);\n"
"font: 40px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 136, 0);\n"
"}")
        self.button_equal.setObjectName("button_equal")
        iOsCalculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(iOsCalculator)
        QtCore.QMetaObject.connectSlotsByName(iOsCalculator)
        self.is_equal = False
        self.add_functions()

    def retranslateUi(self, iOsCalculator):
        _translate = QtCore.QCoreApplication.translate
        iOsCalculator.setWindowTitle(_translate("iOsCalculator", "MainWindow"))
        self.natija_label.setText(_translate("iOsCalculator", "0"))
        self.clear_button.setText(_translate("iOsCalculator", "AC"))
        self.changeDirection_button.setText(_translate("iOsCalculator", "+/-"))
        self.percent_button.setText(_translate("iOsCalculator", "%"))
        self.divide_button.setText(_translate("iOsCalculator", "÷"))
        self.button_8.setText(_translate("iOsCalculator", "8"))
        self.button_7.setText(_translate("iOsCalculator", "7"))
        self.button_9.setText(_translate("iOsCalculator", "9"))
        self.multiply_button.setText(_translate("iOsCalculator", "×"))
        self.button_5.setText(_translate("iOsCalculator", "5"))
        self.button_4.setText(_translate("iOsCalculator", "4"))
        self.button_6.setText(_translate("iOsCalculator", "6"))
        self.minus_button.setText(_translate("iOsCalculator", "-"))
        self.button_2.setText(_translate("iOsCalculator", "2"))
        self.button_1.setText(_translate("iOsCalculator", "1"))
        self.button_3.setText(_translate("iOsCalculator", "3"))
        self.add_button.setText(_translate("iOsCalculator", "+"))
        self.button_0.setText(_translate("iOsCalculator", "0"))
        self.button_comma.setText(_translate("iOsCalculator", "."))
        self.button_equal.setText(_translate("iOsCalculator", "="))

    def add_functions(self):
        self.button_0.clicked.connect(lambda: self.write_number(self.button_0.text()))
        self.button_1.clicked.connect(lambda: self.write_number(self.button_1.text()))
        self.button_2.clicked.connect(lambda: self.write_number(self.button_2.text()))
        self.button_3.clicked.connect(lambda: self.write_number(self.button_3.text()))
        self.button_4.clicked.connect(lambda: self.write_number(self.button_4.text()))
        self.button_5.clicked.connect(lambda: self.write_number(self.button_5.text()))
        self.button_6.clicked.connect(lambda: self.write_number(self.button_6.text()))
        self.button_7.clicked.connect(lambda: self.write_number(self.button_7.text()))
        self.button_8.clicked.connect(lambda: self.write_number(self.button_8.text()))
        self.button_9.clicked.connect(lambda: self.write_number(self.button_9.text()))
        self.button_comma.clicked.connect(lambda: self.write_number(self.button_comma.text()))
        self.add_button.clicked.connect(lambda: self.write_number(self.add_button.text()))
        self.minus_button.clicked.connect(lambda: self.write_number(self.minus_button.text()))
        self.multiply_button.clicked.connect(lambda: self.write_number(self.multiply_button.text()))
        self.divide_button.clicked.connect(lambda: self.write_number(self.divide_button.text()))
        self.percent_button.clicked.connect(lambda: self.write_number(self.percent_button.text()))

        self.button_equal.clicked.connect(self.results)
        self.clear_button.clicked.connect(self.clear)
        
##############################FUNCTIONALS##############################
    def write_number(self, number):
        if self.natija_label.text() == '0' or self.is_equal:
                self.natija_label.setText(number)
                self.is_equal = False
        else:
                self.natija_label.setText(self.natija_label.text() + number)
        

    def results(self):
        prob = self.natija_label.text()
        for i in prob:
                if i == '÷':
                        prob=prob.replace(i, '/')
                if i == '×':
                        prob=prob.replace(i, '*')

        result = eval(prob)
        if int(result) == float(result):
                result = int(result)

        self.natija_label.clear()
        self.natija_label.setText(str(result))
        self.is_equal = True

    def clear(self):  
        self.natija_label.clear()
        self.natija_label.setText('0')

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    iOsCalculator = QtWidgets.QMainWindow()
    ui = Ui_iOsCalculator()
    ui.setupUi(iOsCalculator)
    iOsCalculator.show()
    sys.exit(app.exec_())
